// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAztrhv4-Vnf7z4BszRwyM-Lfwb3d3bPZw',
    appId: '1:73625385104:web:5af397a0e4b669787d4015',
    messagingSenderId: '73625385104',
    projectId: 'app-mobile-47bd1',
    authDomain: 'app-mobile-47bd1.firebaseapp.com',
    storageBucket: 'app-mobile-47bd1.appspot.com',
    measurementId: 'G-Y4GC8CEZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6jg2EwkNnMutNADDEZtu50jGqr25K04',
    appId: '1:73625385104:android:3d6a234b35adad4b7d4015',
    messagingSenderId: '73625385104',
    projectId: 'app-mobile-47bd1',
    storageBucket: 'app-mobile-47bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdlLl0rriayO-PivMAqVvdPw0WhZNlbU',
    appId: '1:73625385104:ios:43232183959af46c7d4015',
    messagingSenderId: '73625385104',
    projectId: 'app-mobile-47bd1',
    storageBucket: 'app-mobile-47bd1.appspot.com',
    iosBundleId: 'com.example.clasePractica4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmdlLl0rriayO-PivMAqVvdPw0WhZNlbU',
    appId: '1:73625385104:ios:43232183959af46c7d4015',
    messagingSenderId: '73625385104',
    projectId: 'app-mobile-47bd1',
    storageBucket: 'app-mobile-47bd1.appspot.com',
    iosBundleId: 'com.example.clasePractica4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAztrhv4-Vnf7z4BszRwyM-Lfwb3d3bPZw',
    appId: '1:73625385104:web:c9787aedf84488f17d4015',
    messagingSenderId: '73625385104',
    projectId: 'app-mobile-47bd1',
    authDomain: 'app-mobile-47bd1.firebaseapp.com',
    storageBucket: 'app-mobile-47bd1.appspot.com',
    measurementId: 'G-2MG2F72D3H',
  );
}
